apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: app-config
data:
  PHX_HOST: {{ .Values.app.host }}
  GITLAB_CLIENT_ID: {{ .Values.app.gitlabClientId }}
  GITLAB_SITE: {{ .Values.app.gitlabSite }}
  {{ if .Values.app.listId }}
  DEFAULT_LIST_ID: {{ .Values.app.listId | quote }}
  {{ end }}
