apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: app-secret
data:
  SECRET_KEY_BASE: {{ required "A valid .Values.app.secretKeyBase entry required!" .Values.app.secretKeyBase | b64enc }}
  GITLAB_CLIENT_SECRET: {{ .Values.app.gitlabClientSecret | b64enc }}
